project:
  type: website
  output-dir: docs

website:
  title: "asymptotic to MARS"
  navbar:
    left:
      - href: index.qmd
        text: Bried Notes
      - about.qmd
      - favourites.qmd

format:
  html:
    theme:
      light: minty
      dark: darkly
    #theme: thestylishtheme.scss
    toc: true

editor: visual

