---
title: "Example 2"
---

# Example 2:

Consider a spin-1/2 particle whose energy eigenstates and eigenvalues are given by $|n\rangle$ and $E_n=n^2 E_1$ for $n=1,2,..$

Assume we have a system with two of these particles, which do not interact.

1.  Write the ground state and first excited states when the total spin is zero $S=0$. What are the corresponding eigenvalues?
2.  What is the ground state when the total spin is $1$?

Answer:

The single particle states are of the form $|\text{spacial}\rangle \otimes|\text{spin}\rangle$ where

$$
\begin{align}
&|\text{spacial}\rangle \in \text{span}\{\text{Eigenstates of $h$ }\}\\
&|\text{spin}\rangle \in \text{span}\{\text{Eigenstates of $S^2$ and $S_z$}\}
\end{align}
$$

More concretely we have $|n\rangle\otimes |m\rangle$ with $n=1,2,..$ and $m=\pm1/2$; usually written as $|n,m\rangle$.

Why are the single particle eigenstates of this form? Answer: The observables $\{h,S^2,S_z\}$ commutes (common eigenvectors exists) and the operators are independent ($h$ is not a function of either $S^2$ or $S_z$) and thus it suffices to specify the quantum numbers of each operator (the quantum number $s=1/2$ is suppressed in the notation)

The possible quantum states of the total system are the eigenstates of the observables $\{H,S_1^2,S_{1z}, S_2^2,S_{2z} \}$ with the total Hamiltonian as $H = h_1 +h_2+V_{12}$ where $V_{12}$ is zero since we are assuming non-interaction particles. We should look at these operators as extensions, for example the Hamiltonian is:

$$
h_1 \otimes 1_2 \otimes 1_{s1} \otimes 1_{s2}+ 1_1 \otimes h_2 \otimes 1_{s1} \otimes 1_{s2}
$$

with

$$ h_i|i:n_i\rangle =n_i^2E_1|i:n_i\rangle $$

The eigenstates of the system are of the form:

$$
|1:n_1,m_1\rangle \otimes |2:n_2,m_2\rangle
$$

which can be written more compactly as:

$$
|n_1,n_2\rangle \otimes |m_1,m_2\rangle
$$

Hence for $i=1,2$:

$$
\begin{align}
&H|n_1,n_2\rangle \otimes |m_1,m_2\rangle = \frac{n_1^2+n_2^2}{2I}E_1|n_1,n_2\rangle \otimes |m_1,m_2\rangle\\
&S^2_i|n_1,n_2\rangle \otimes |m_1,m_2\rangle = \frac{3\hbar^2}{4}|n_1,n_2\rangle \otimes |m_1,m_2\rangle\\
&S_{iz}|n_1,n_2\rangle \otimes |m_1,m_2\rangle = m_i\hbar |n_1,n_2\rangle \otimes |m_1,m_2\rangle
\end{align}
$$

The two question posed refer to the total spin of the system, so it is a good idea to change the spin basis and write the spin part involving the total spin. We know from the previous theory that:

$$
\text{span}\{|n_1,n_2\rangle \otimes |m_1,m_2\rangle\} = \text{span}\{|n_1,n_2\rangle \otimes |S,M\rangle\}
$$

Where again we suppress from the spin part this: $|\overbrace{1/2,1/2},S,M\rangle$

$$
\begin{align}
&H|n_1,n_2\rangle \otimes |S,M\rangle = \frac{n_1^2+n_2^2}{2I}E_1|n_1,n_2\rangle \otimes |S,M\rangle\\
&S^2_i|n_1,n_2\rangle \otimes |S,M\rangle = \frac{3\hbar^2}{4}|n_1,n_2\rangle \otimes |S,M\rangle\\
&S^2|n_1,n_2\rangle \otimes |S,M\rangle = S(S+1)\hbar^2|n_1,n_2\rangle \otimes |S,M\rangle\\
&S_{z}|n_1,n_2\rangle \otimes |S,M\rangle = M\hbar |n_1,n_2\rangle \otimes |S,M\rangle
\end{align}
$$

1.  We want the states of the form $|n_1,n_2\rangle \otimes |S,M\rangle$ such that the following statements are true:

    $$
    \begin{cases}
    P_{21}|n_1,n_2\rangle \otimes |S,M\rangle =-1\times|n_1,n_2\rangle \otimes |S,M\rangle\\
    |S,M\rangle = |S=0,M=0\rangle\\
    \frac{n_1^2+n_2^2}{2I}E_1\quad \text{is minimum}
    \end{cases}
    $$ Since the spin part is antissimetric:

    $$
    \begin{align}
    P_{21} |0,0\rangle &= P_{21} \frac{1}{\sqrt{2}}(|1:\uparrow,2:\downarrow\rangle - |1:\downarrow,2:\uparrow\rangle ) \\
    &= -1\times \frac{1}{\sqrt{2}}(|1:\uparrow,2:\downarrow\rangle - |1:\downarrow,2:\uparrow\rangle )\\
    &-1\times |0,0\rangle
    \end{align}
    $$ we seek a spacial ket that is symmetric and whose energy is minimum.

    The spacial state $n_1=n_2=1$ statisfies the criteria. Therefore the final answer is:

    $$
    |1,1\rangle\otimes|0,0\rangle
    $$

    or

    $$
    |1,1\rangle \otimes \frac{1}{\sqrt{2}}(|1:\uparrow,2:\downarrow\rangle - |1:\downarrow,2:\uparrow\rangle )
    $$

    whose eigenvalue is $(1^2 + 1^2) E_1$.

    Following a similar line of reasoning the first excited state with $S=0$ must be:

    $$
    \frac{1}{\sqrt{2}}(|2,1\rangle + |1,2\rangle) \otimes |0,0\rangle
    $$

    Observe that the spacial spate is symmetric when we use the $+$ sign!

2.  When $S=1$ the spin state is one of the symetric triplet states:

    \$\$

    \begin{align}
    &\ket{1,1}=\ket{1/2,1/2}\\
    &\ket{1,0}=\frac{1}{\sqrt{2}}\left(\ket{-\frac{1}{2},\frac{1}{2}}+\ket{\frac{1}{2},-\frac{1}{2}}\right)\\
    &\ket{1,-1}=\ket{-1/2,-1/2}
    \end{align} \$\$

    As a result the spacial part must be antissymetric for the whole quantum state of the two particles to be antissymetric as PEP requires. Thus:

    $$
    \begin{align}
    &\frac{1}{\sqrt{2}}(|2,1\rangle - |1,2\rangle)\otimes |1,1\rangle\\
    &\frac{1}{\sqrt{2}}(|2,1\rangle - |1,2\rangle)\otimes |1,0\rangle\\
    &\frac{1}{\sqrt{2}}(|2,1\rangle - |1,2\rangle)\otimes |1,-1\rangle\\
    \end{align}
    $$

    Notice the minimum energy AND antissymetry of the spacial part only occurs at the FIRST excited state. The spacial ground state is the symmetric $|1,1\rangle$.
