---
title: "Examples_of_functions"
---

# Examples of functions

Some examples illustrate again [Definition 1](functions_as_relations.qmd#def-funcrel) in practice:

::: {#exm-Fs}
Let $X=\{a,b,c\}$ and $Y=\{1,2\}$. All possible pairs are listed in the cartesian product $X \times Y=\{(a,1),(a,2),(b,1),(b,2),(c,1),(c,2)\}$. Relations and functions are subsets of the cartesian product, give some examples.
:::

::: {#sol-Fs}
A special subset of these pairs is the function $F\coloneqq \{(a,1),(b,1),(c,2)\}$. The domain of this function is $\{a,b,c\}$ since these are all the $x$'s in $F$; the codomain is $Y$ and the range which contains all $y$'s of $F$ is $R_F=\{1,2\}$. Another subset of $X \times Y$ could be $G\coloneqq \{(a,1),(b,1),(c,2),(a,2)\}$, it is not special since the element $a$ is associated with two distinct elements $1$ and $2$, thus appearing twice, rendering [Equation 3](functions_as_relations.qmd#eq-deffunc) a false statement. This subset is not a function, but it is a relation whose domain is $\{a,b,c\}$ and range $\{1,2\}$.

The list $H\coloneqq\{(a,1),(b,1)\}$ is a function whose domain is $\{a,b\}$ which is a subset of $X$ and range is just $\{1\}$ which is a subset of the codomain $Y$. We see that not every element of $X$ or $Y$ have to be used in defining a function.
:::

::: {#exm-Gs}
Now consider the set of natural numbers $\mathbb{N}$ and the set of all pairs $\mathbb{N}\times \mathbb{N}$. Illustrate examples of functions.
:::

::: {#sol-Gs}
The special subset $G\coloneqq \{(9,1),(4,4),(1,9)\}$ is a function where the domain and range are the same set $D_G=R_G=\{1,4,9\}$. The sets $\{(1,1),(2,1),(3,1)\}$ and $\{(3,1),(5,1),(13,1)\}$ are also functions, but $\{(1,1),(1,2),(3,1)\}$ is not.
:::

::: {#exm-Hs}
Consider now the set $\mathbb{R}\times \mathbb{R}$. The truth set of the statement $y=x^2$ is the subset of all pairs $(x,y)$ that make it true, formally we write $\{(x,y)\in \mathbb{R}\times \mathbb{R}\,|\,\,y=x^2\}$. This list of pairs is special since for every real $x$ we choose, the calculation $x^2$ yields a single number, which is always positive or zero. What is the domain, codomain and range?
:::

::: {#sol-Hs}
The pairs of this set come from the cartesian product $\mathbb{R}\times \mathbb{R}$, the proposition $y=x^2$ does not put any restriction on the choice of $x$, thus $x$ can take any real value, meaning the domain is $\mathbb{R}$. On the other hand, this proposition demands that $y$ be positive or zero, because $x^2$ it is for any $x$ in the domain, as a result the range is just the positive reals or zero $\mathbb{R}^+_0$.
:::

::: {#exr-q_13}
Consider the sets $A\coloneqq \{(x,y) \in \mathbb{R}\times\mathbb{R}\,|\,\, y=1\}$ and $B\coloneqq \{(x,y) \in \mathbb{R}\times \mathbb{R}\,|\,\, x=1\}$. Convince yourself whether it is or not a function using the [Definition 1](functions_as_relations.qmd#def-funcrel). For both specify the domain, range and codomain. What about $B'\coloneqq \{(x,y) \in \mathbb{R}\times \{2\}\,|\,\, x=1\}$? [Solution](question_q_13.qmd){style="color: yellow"}
:::

::: {#exr-qu_131}
With $X\coloneqq \{\alpha,\beta,\gamma,\delta\}$ and $Y\coloneqq \{1,2,3,4\}$ create relations, two that are not functions and two that are. Make sure you create function, which use all $X$ and others that do not. [Solution](qu_131.qmd)
:::
